version: '3.9'
services:

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

  indexer:
    build: ./indexer
    volumes:
      - ${LOCAL_FILES_PATH}:/usr/src/app/local_files/
      - ./indexer:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - START_INDEXING=${START_INDEXING}
    depends_on:
      - qdrant

  linker:
    build: ./linker
    volumes:
      - ./linker:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - FIRESTORE_COLLECTION_NAME=userTasks
      - TASKS_COLLECTION=tasks
      - USER_ID=${USER_ID}
      - PASSWORD=${PASSWORD}
      - FB_PROJECT=localragex
    depends_on:
      - qdrant